; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30137.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	first_number:DWORD
COMM	second_number:DWORD
COMM	addition_of_both:DWORD
_DATA	ENDS
PUBLIC	main
EXTRN	printf:PROC
EXTRN	exit:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+81
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG6144	DB	'Addition of both number is %d, we processed', 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\Sangameshwar\OneDrive\PRACTICE_PROGRAME\09-12-2021\SUMMATION\berij.c
; Line 9
$LN3:
	sub	rsp, 40					; 00000028H
; Line 10
	mov	DWORD PTR first_number, 38		; 00000026H
; Line 11
	mov	DWORD PTR second_number, 0
; Line 12
	mov	eax, DWORD PTR second_number
	mov	ecx, DWORD PTR first_number
	add	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR addition_of_both, eax
; Line 14
	mov	edx, DWORD PTR addition_of_both
	lea	rcx, OFFSET FLAT:$SG6144
	call	printf
; Line 16
	mov	ecx, 1
	call	exit
; Line 18
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
